machine:
  python:
    version: 3.5.2

dependencies:
  override:
    - pip install -r requirements.txt

deployment:
    master:
        branch: master
        commands:
            - python setup.py sdist
